apiVersion: v1
kind: Service
metadata:
  name: {{ include "three.fullname" . }}
  labels:
    {{- include "three.labels" . | nindent 4 }}
spec:
  type: {{ .Values.front.service.type }}
  ports:
    - port: {{ .Values.front.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "three.selectorLabels" . | nindent 4 }}
